### ISSUE TITLE
certain missing widths are confusing

### ISSUE THREAD

**Issue by ianstormtaylor** [tachyons-css/tachyons-widths#6]
I keep trying to add a few different percentage widths that aren't available:
- `w-66` `w-67`
- `w-30`
- `w-70`

And it looks like for completeness it might be nice to add:
- `w-90`

What do you think?

**Comment by mrmrs** [comment]
@ianstormtaylor Ha could have really used your thoughts over the last 2_ years. Have gone back and forth on this a million times. If you look at the history you'd probably see most of those available at some point :) 

The 33/34/33 is a holdover from an old pattern I used and it wasn't meant to be matched with 2/3 or 67. But I get how it looks when reviewing just the available values.

Most of the things in tachyons are 'what do I need all of the time when I make websites'. and I rarely if ever find that I need 66,67,30,70,90% widths. But I also haven't been doing a bunch of crazy stuff with tables. 

I'm not opposed to adding them in v4 - but curious as to what needs them? Is it more that you'd expect them to be there and they are not? Or you need them to build a certain pattern and they are not there?

**Comment by ianstormtaylor** [comment]
Totally could be a fault of me not quite "getting it" yet! Let's see if I can explain my thinking...

For most of the layout widths, I'd usually try to use `measure` or `mw7` or some form of that. 

But then there are special cases where I get into the weeds with some little piece I'm trying to layout on a landing page where I think, "I'll split it 1/3 and 2/3 to get the right feel". And then I hit the wall. Or similar, sometimes I just want to make a tweak where something needs to go from `100%` to `90%` just to "feel" right.

I guess for me it comes down to what tachyons's goal is. I interpret its goal as something along the lines of: 

> Letting you scaffold layout/scale/rhythm decisions on the fly in HTML, since they are so impossible to properly abstract. Separate known "components" out like buttons and headers for sure, but don't couple the margins, paddings, widths, etc. to those components. Instead, chuck that stuff in the HTML because it changes so much even with small additions to the page.

Along those lines, I just kind of assumed that tachyons's API goal would be to expose all of the barebones CSS hooks that you need to be able to set up the proper layout/scale/rhythm via classes. 

In which case I'd just try to make it "simple" by exposing a knowable system of widths:
- scale increments
- percentage increments of `10`
- percentage common ratios
- common keywords

And call it done.

But, that's kind of assuming that tachyons doesn't have a "right way" to go about thinking about how to achieve layout itself. (Only assuming a "right" way in terms of how it prescribes separation of concerns.) If there is a "right way" to layout, then it's totally possible that I just don't know it yet, and that the "right way" would involve never needing to use `90%` or `67%`.

Does that make sense?

I feel like my ideal tachyons would be super easily auto-generate-able from JS 😄  which would correspond to it's system being fairly strict and predictable.

**Comment by mrmrs** [comment]
No it totally makes sense. 

And yeah we are working on a generator for just that! We'll share soon so we can get feedback.

Honestly for most of tachyons - it was really just 'these are patterns I personally use all the time' 
and nothing more. Which has made me hesitate to add anything I'm not personally using a lot. But as people are using it for their own projects - while I don't think I can solve all problems for everyone - I do think there is room for improvement on helping people cover common use cases. So if we had 

third
two-thirds
10,20,25,30,40,50,60,70,75,80,90,100 

This would be cover everything you think? I'd be up of for adding that to v4.5

**Comment by ianstormtaylor** [comment]
Yup! Those additions would be the changes I'd make to "fill out" all of the existing width systems. Although I'm not sure how `third/two-thirds` are implemented, and whether the extra `1%` matters.

**Comment by mrkhdly** [comment]
Tachyons v5 will become a monorepo so this issue is being closed, if the issue is still relevant please open an issue with the main repo https://github.com/tachyons-css/tachyons/issues/new & link to this one
